/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DividendVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "businessStock"
      | "claimDividends"
      | "claimedDividends"
      | "depositProfit"
      | "stablecoin"
      | "totalDividendsDeposited"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DividendsClaimed" | "DividendsDeposited"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "businessStock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimDividends",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimedDividends",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositProfit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDividendsDeposited",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "businessStock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDividends",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedDividends",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositProfit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalDividendsDeposited",
    data: BytesLike
  ): Result;
}

export namespace DividendsClaimedEvent {
  export type InputTuple = [investor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [investor: string, amount: bigint];
  export interface OutputObject {
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendsDepositedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DividendVault extends BaseContract {
  connect(runner?: ContractRunner | null): DividendVault;
  waitForDeployment(): Promise<this>;

  interface: DividendVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  businessStock: TypedContractMethod<[], [string], "view">;

  claimDividends: TypedContractMethod<[], [void], "nonpayable">;

  claimedDividends: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  depositProfit: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stablecoin: TypedContractMethod<[], [string], "view">;

  totalDividendsDeposited: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "businessStock"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimDividends"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedDividends"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositProfit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalDividendsDeposited"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DividendsClaimed"
  ): TypedContractEvent<
    DividendsClaimedEvent.InputTuple,
    DividendsClaimedEvent.OutputTuple,
    DividendsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DividendsDeposited"
  ): TypedContractEvent<
    DividendsDepositedEvent.InputTuple,
    DividendsDepositedEvent.OutputTuple,
    DividendsDepositedEvent.OutputObject
  >;

  filters: {
    "DividendsClaimed(address,uint256)": TypedContractEvent<
      DividendsClaimedEvent.InputTuple,
      DividendsClaimedEvent.OutputTuple,
      DividendsClaimedEvent.OutputObject
    >;
    DividendsClaimed: TypedContractEvent<
      DividendsClaimedEvent.InputTuple,
      DividendsClaimedEvent.OutputTuple,
      DividendsClaimedEvent.OutputObject
    >;

    "DividendsDeposited(uint256)": TypedContractEvent<
      DividendsDepositedEvent.InputTuple,
      DividendsDepositedEvent.OutputTuple,
      DividendsDepositedEvent.OutputObject
    >;
    DividendsDeposited: TypedContractEvent<
      DividendsDepositedEvent.InputTuple,
      DividendsDepositedEvent.OutputTuple,
      DividendsDepositedEvent.OutputObject
    >;
  };
}
