/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockZKVerifierInterface extends Interface {
  getFunction(nameOrSignature: "verifyIdentity"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VerificationSuccessful"): EventFragment;

  encodeFunctionData(
    functionFragment: "verifyIdentity",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "verifyIdentity",
    data: BytesLike
  ): Result;
}

export namespace VerificationSuccessfulEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockZKVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): MockZKVerifier;
  waitForDeployment(): Promise<this>;

  interface: MockZKVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verifyIdentity: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verifyIdentity"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;

  getEvent(
    key: "VerificationSuccessful"
  ): TypedContractEvent<
    VerificationSuccessfulEvent.InputTuple,
    VerificationSuccessfulEvent.OutputTuple,
    VerificationSuccessfulEvent.OutputObject
  >;

  filters: {
    "VerificationSuccessful(address)": TypedContractEvent<
      VerificationSuccessfulEvent.InputTuple,
      VerificationSuccessfulEvent.OutputTuple,
      VerificationSuccessfulEvent.OutputObject
    >;
    VerificationSuccessful: TypedContractEvent<
      VerificationSuccessfulEvent.InputTuple,
      VerificationSuccessfulEvent.OutputTuple,
      VerificationSuccessfulEvent.OutputObject
    >;
  };
}
