export const mockBusinesses = [
  {
    id: 1,
    name: "Green Earth Café",
    type: "Food & Beverage",
    category: "food",
    image: "https://images.pexels.com/photos/1855214/pexels-photo-1855214.jpeg",
    description: "Sustainable, organic café seeking expansion to new locations.",
    fullDescription: "Green Earth Café is a loved local spot that prioritizes sustainability and organic ingredients. We are looking to expand our operations and open a second location downtown to meet growing demand.",
    percentAvailable: 40,
    valuation: "$450,000",
    dividendYield: "8.5%",
    investorCount: 124,
    minimumInvestment: 100,
    status: "active",
    location: "123 Main St, Springfield",
    founded: "2020",
    employees: 12,
    revenue: "$350,000",
    profitMargin: "15%",
    tokenPrice: "10",
    fundingProgress: 65,
    amountRaised: "117,000",
    fundingGoal: "180,000"
  },
  {
    id: 2,
    name: "Bright Smile Dental",
    type: "Healthcare",
    category: "health",
    image: "https://images.pexels.com/photos/3881445/pexels-photo-3881445.jpeg",
    description: "Modern dental practice looking to invest in advanced equipment.",
    fullDescription: "Bright Smile Dental offers state-of-the-art dental care. Community investment will allow us to purchase advanced 3D imaging equipment, expanding our service offerings.",
    percentAvailable: 25,
    valuation: "$750,000",
    dividendYield: "7.2%",
    investorCount: 89,
    minimumInvestment: 500,
    status: "active",
    location: "456 Oak Rd, Springfield",
    founded: "2018",
    employees: 8,
    revenue: "$850,000",
    profitMargin: "22%",
    tokenPrice: "50",
    fundingProgress: 40,
    amountRaised: "75,000",
    fundingGoal: "187,500"
  },
  {
    id: 3,
    name: "Harbor Bookstore",
    type: "Retail",
    category: "retail",
    image: "https://images.pexels.com/photos/1370295/pexels-photo-1370295.jpeg",
    description: "Independent bookstore expanding its community events program.",
    fullDescription: "More than just a bookstore, Harbor Bookstore is a community hub. We're raising funds to expand our event space to host more author talks, workshops, and community gatherings.",
    percentAvailable: 35,
    valuation: "$320,000",
    dividendYield: "6.8%",
    investorCount: 215,
    minimumInvestment: 50,
    status: "active",
    location: "789 Pine Ln, Springfield",
    founded: "2015",
    employees: 5,
    revenue: "$210,000",
    profitMargin: "12%",
    tokenPrice: "5",
    fundingProgress: 85,
    amountRaised: "95,200",
    fundingGoal: "112,000"
  },
  {
    id: 4,
    name: "TechFix Solutions",
    type: "Technology",
    category: "tech",
    image: "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg",
    description: "Local IT repair and business solutions provider scaling operations.",
    fullDescription: "TechFix Solutions provides essential IT services to local businesses and residents. We are seeking investment to open a larger repair facility and hire additional technicians.",
    percentAvailable: 30,
    valuation: "$600,000",
    dividendYield: "9.5%",
    investorCount: 156,
    minimumInvestment: 200,
    status: "active",
    location: "321 Tech Blvd, Springfield",
    founded: "2019",
    employees: 15,
    revenue: "$550,000",
    profitMargin: "18%",
    tokenPrice: "20",
    fundingProgress: 55,
    amountRaised: "99,000",
    fundingGoal: "180,000"
  }
];
