/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockZKVerifier,
  MockZKVerifierInterface,
} from "../../contracts/MockZKVerifier";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "VerificationSuccessful",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "verifyIdentity",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060be8061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063b5b90fd914602d575b600080fd5b60466038366004605a565b6001600160a01b0316151590565b604051901515815260200160405180910390f35b600060208284031215606b57600080fd5b81356001600160a01b0381168114608157600080fd5b939250505056fea264697066735822122090705d0af65e2254ae908088ff61ffeb18058de3bac08477834e364cf49e742364736f6c63430008180033";

type MockZKVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockZKVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockZKVerifier__factory extends ContractFactory {
  constructor(...args: MockZKVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockZKVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockZKVerifier__factory {
    return super.connect(runner) as MockZKVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockZKVerifierInterface {
    return new Interface(_abi) as MockZKVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockZKVerifier {
    return new Contract(address, _abi, runner) as unknown as MockZKVerifier;
  }
}
